version: 2.1

jobs:
  run-tests:
    docker:
      - image: golang:latest
    steps:
      - checkout
      - run: go get -u golang.org/x/lint/golint
      - run: bash ./test.sh

workflows:
  test-workflow:
    jobs:
      - run-tests
