version: 2.1

jobs:
  run-tests:
    docker:
      - image: golang:latest
    steps:
      - checkout
      - run:
          name: "Tests"
          command: ./test.sh"

workflows:
  test-workflow:
    jobs:
      - run-tests
